/*
 * confpaths.h — Android build.
 *
 * Normally generated by autotools (defines install paths like PKGDATADIR). On Android
 * the app's data lives in assets / app-private storage resolved at runtime via
 * SDL_AndroidGetInternalStoragePath(), not a compiled-in prefix, so we leave PKGDATADIR
 * undefined — cspaths_sdl.cpp guards its use with #ifdef PKGDATADIR.
 */
/* #define PKGDATADIR "" */
