/*
 * config.h — hand-written for the Android/NDK build (Phase 0 of the VR port).
 *
 * On desktop this file is generated by autotools (configure). On Android we provide it
 * directly and enable only the features in the Phase-0 dependency set.
 * See docs/ANDROID_BUILD.md §2. Add HAVE_* lines here as deps come online.
 */
#ifndef ALEPHONE_ANDROID_CONFIG_H
#define ALEPHONE_ANDROID_CONFIG_H

/* Package identity (normally from configure.ac / alephversion.h) */
#define PACKAGE        "AlephOne"
#define PACKAGE_NAME   "Aleph One"
#define PACKAGE_TARNAME "alephone"
#define TARGET_PLATFORM "android arm64"

/* Platform headers/functions present on Android */
#define HAVE_UNISTD_H 1
#define HAVE_PWD_H    1
#define HAVE_SNPRINTF 1
#define HAVE_VSNPRINTF 1
#define LUA_USE_MKSTEMP 1

/* Enabled features */
#define HAVE_SDL_IMAGE 1
#define HAVE_OPENGL    1   /* GLES3 path in OGL_Headers.h */

/* The software renderer is 2.5D (column/span raycast with a y-shear fake for pitch) and
 * cannot do VR, so it is NOT a target here. The OpenGL/shader renderer is true 3D (real
 * perspective frustum + 3D pitch when OGL_Flag_MimicSW is off) and is the only viable path.
 * It currently uses fixed-function GL that does not exist in GLES3, so the engine will not
 * fully link until the Phase 1 renderer modernization lands. Toolchain is validated first
 * with a minimal SDL+GLES smoke app (android/jni/smoke_main.cpp, A1_SMOKE_TEST option).
 *
 * UNDEFINED for first boot (add as ported):
 *   HAVE_CURL, HAVE_ZZIP, HAVE_PNG, HAVE_MINIUPNPC, HAVE_NFD,
 *   HAVE_STEAM, FILM_EXPORT, HAVE_MATROSKA, HAVE_VPX, HAVE_EBML,
 *   HAVE_VORBIS, HAVE_VORBISENC, HAVE_LIBYUV, HAVE_CATCH2
 */

#endif /* ALEPHONE_ANDROID_CONFIG_H */
