name: mac-osx
description: template used to build for mac osx

inputs:
 vcpkg_installed_folder:
    required: true
    type: string
 vcpkg_arch:
    required: true
    type: string
 xcode_arch:
    required: true
    type: string

runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v2
    
    - name: Install Tools
      run: brew install nasm automake
      shell: bash
      
    - name: Vcpkg Integration
      run: $VCPKG_INSTALLATION_ROOT/vcpkg integrate install
      shell: bash
      
    - name: Cache Vcpkg
      uses: actions/cache@v2
      with:
        path: vcpkg/${{inputs.vcpkg_installed_folder}}
        key: ${{runner.os}}-${{inputs.vcpkg_installed_folder}}-${{hashFiles('**/vcpkg.json')}}
      
    - name: Switch to Xcode 12.5.1
      run: sudo xcode-select --switch /Applications/Xcode_12.5.1.app
      shell: bash
      
    - name: Install Dependencies
      run: cd vcpkg && ./install-${{inputs.vcpkg_arch}}-osx.sh
      shell: bash
      
    - name: Build
      run: cd PBProjects && xcodebuild -arch ${{inputs.xcode_arch}} -target "Aleph One" TEAM_ID='' DEVELOPMENT_TEAM='' CODE_SIGNING_REQUIRED='NO' CODE_SIGN_IDENTITY='' CODE_SIGN_STYLE='' build
      shell: bash