name: release-steam-linux

on: [workflow_dispatch, workflow_call]

jobs:
  release:
    runs-on: ubuntu-24.04
    container: registry.gitlab.steamos.cloud/steamrt/sniper/sdk
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure
      uses: ./.github/actions/configure-linux
      with:
        use_vcpkg: true
        configure_options: >
            --enable-steam --with-boost=/vcpkg/installed-x64-linux/x64-linux
            CXXFLAGS=-I/vcpkg/installed-x64-linux/x64-linux/include 
            LDFLAGS=-L/vcpkg/installed-x64-linux/x64-linux/lib 
            matroska_CFLAGS=-I/vcpkg/installed-x64-linux/x64-linux/include 
            matroska_LIBS="-L/vcpkg/installed-x64-linux/x64-linux/lib -lmatroska -lebml" 
            ebml_CFLAGS=-I/vcpkg/installed-x64-linux/x64-linux/include 
            ebml_LIBS="-L/vcpkg/installed-x64-linux/x64-linux/lib -lebml"
        
    - name: Build
      run: make -j $(nproc)
